version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spr_app
    restart: unless-stopped
    user: "1001:1001"
    volumes:
      - type: bind
        source: /opt/spr_project
        target: /var/www
    working_dir: /var/www
    ports:
      - "127.0.0.1:9002:9000"  # Expose PHP-FPM locally
    networks:
      - spr_network

  db:
    image: mariadb:10.6
    container_name: spr_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: spr_db
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_PASSWORD: dbpassword
      MYSQL_USER: dbuser
    volumes:
      - spr_dbdata:/var/lib/mysql
    networks:
      - spr_network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: spr_portainer
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - portainer_data:/data
    ports:
      - "127.0.0.1:9001:9000"  # Only expose locally
    networks:
      - spr_network

networks:
  spr_network:
    driver: bridge

volumes:
  spr_dbdata:
  portainer_data: